calabash/calabash

calabash.gemspec

**FORCE PUSHED** Mon Jan 12 15:14 CET
Run loop 1.2 needs fix in awesome-print 1.6

Feature/update gemspec for run-loop and awesome-print

---

lib/calabash/http/retriable_client.rb
spec/lib/http/retriable_client_spec.rb

https://travis-ci.org/calabash/calabash/builds/55491614

Fixup retriable-client examples

---

lib/calabash.rb
lib/calabash/environment.rb
lib/calabash/wait.rb
spec/lib/wait_spec.rb
spec/spec_helper.rb

Signed-off-by: Joshua Moody <joshuajmoody@gmail.com>

Add Wait methods

---

lib/calabash/ios/device.rb
spec/lib/ios/device_spec.rb

Finish up the iOS Device unit tests.

iOS:Device start app example

---

calabash.gemspec

Preparing for integration tests.

Add calabash/luffa gem dependency

---

lib/calabash/ios/device.rb
spec/integration/ios/device_spec.rb
spec/lib/ios/device_spec.rb

I started to implement the whole API, but things got really tricky around #install_app so I decided to implement Device API incrementally.
* calabash_stop_app
* screenshot

iOS Device API contract: stop_app and screenshot

---

lib/calabash/device.rb
lib/calabash/environment.rb
lib/calabash/ios/application.rb
lib/calabash/ios/device.rb
lib/calabash/ios/environment.rb
spec/lib/ios/device_spec.rb

iOS docs:  Device, Application, and Environment

---

lib/calabash/android/device.rb
lib/calabash/device.rb
lib/calabash/ios/device.rb
spec/integration/ios/device_spec.rb
spec/lib/android/device_spec.rb
spec/lib/device_spec.rb
spec/lib/ios/device_spec.rb

@TobiasRoikjer This contains the Device API change I proposed here #78 
I am going to merge.  We can revert in necessary.

iOS Device API:  clear_app_data

---

lib/calabash/android/device.rb
lib/calabash/device.rb
lib/calabash/ios/device.rb
spec/integration/ios/device_spec.rb
spec/lib/device_spec.rb
spec/lib/ios/device_spec.rb

@TobiasRoikjer This contains the Device API change I proposed here #78 
I am going to merge.  We can revert in necessary.

iOS Device API:  #uninstall_app

---

cucumber/ios/.irbrc
cucumber/ios/Gemfile
cucumber/ios/Gemfile.lock
cucumber/ios/config/cucumber.yml
cucumber/ios/features/keyboard.feature
cucumber/ios/features/scroll.feature
cucumber/ios/features/step_definitions/calabash_example_steps.rb
cucumber/ios/features/support/env.rb
cucumber/ios/features/support/hooks.rb

Need a way to test iOS Gesture API.

iOS: scaffolding for cucumber testing

---

README.md
cucumber/ios/.irbrc
cucumber/ios/Gemfile
cucumber/ios/Gemfile.lock
cucumber/ios/features/step_definitions/calabash_example_steps.rb
lib/calabash.rb
lib/calabash/android.rb
lib/calabash/http/retriable_client.rb
lib/calabash/ios.rb
lib/calabash/ios/device.rb
lib/calabash/ios/operations.rb
lib/calabash/ios/routes/map_route.rb
lib/calabash/operations.rb
script/backwards_compatibility.rb
spec/lib/ios/routes/map_route_spec.rb

I want to be able to run come cucumbers!
@krukow

iOS:  Map route to implement query

---

lib/calabash/operations.rb
spec/lib/operations_spec.rb

I believe this should be in operations.
@TobiasRoikjer Move it if you disagree.

Ops: add #escape_single_quotes

---

cucumber/ios/Gemfile.lock
cucumber/ios/features/step_definitions/calabash_example_steps.rb
cucumber/ios/features/support/env.rb
lib/calabash/ios.rb
lib/calabash/ios/device.rb
lib/calabash/ios/routes/uia_route.rb
spec/lib/ios/device_spec.rb
spec/lib/ios/routes/uia_route_spec.rb

iOS UIA route

---

lib/calabash/ios.rb
lib/calabash/ios/device.rb
lib/calabash/ios/gestures.rb
lib/calabash/ios/routes/uia_route.rb
lib/calabash/operations.rb
spec/lib/ios/routes/uia_route_spec.rb
spec/lib/operations_spec.rb

```
$ cd cucumber/ios
$ bundle
$ be cucumber -t @wip
```

iOS: tap gesture

---

lib/calabash/ios.rb
lib/calabash/ios/device.rb
lib/calabash/ios/status_bar.rb
spec/lib/ios/status_bar_spec.rb

iOS: status-bar-orienation

---

calabash.gemspec

Gem: remove retriable dependency

---

lib/calabash/wait.rb
spec/lib/wait_spec.rb

**Remove :post_timeout from Wait options or implement it.** #102

Wait: remove :post_timeout option

---

lib/calabash/ios.rb
lib/calabash/ios/device/device.rb
lib/calabash/ios/device/gestures_mixin.rb
lib/calabash/ios/device/routes/handle_route_mixin.rb
lib/calabash/ios/device/routes/map_route_mixin.rb
lib/calabash/ios/device/routes/uia_route_mixin.rb
spec/lib/ios/device/gestures.rb
spec/lib/ios/device/gestures_mixin_spec.rb
spec/lib/ios/device/routes/handle_route_mixin_spec.rb
spec/lib/ios/device/routes/map_route_mixin_spec.rb
spec/lib/ios/device/routes/uia_route_mixin_spec.rb

http://en.wikipedia.org/wiki/Mixin
I want to be able to visually understand what is getting included in Calabash::IOS::Device.

iOS Apply mixin pattern for device mixins

---

lib/calabash/http/retriable_client.rb
spec/lib/http/retriable_client_spec.rb

Android needs the Content-Type to be set to "application/json;charset=utf-8" or the server will response with an NPE.
Tobias, should we bother with a unit test here?  If not, would you mind writing the specs?

HTTP: Set the http header

---

lib/calabash/http/retriable_client.rb
spec/lib/http/retriable_client_spec.rb

Finishes the TODO in [**HTTP: Set the http header**](#126)
Many thanks to @michaelkirk!

Examples for RetriableClient#request

---

cucumber/ios/features/step_definitions/backdoor_steps.rb
lib/calabash/ios/device.rb
lib/calabash/ios/device/device.rb
lib/calabash/ios/device/routes/backdoor_route_mixin.rb
lib/calabash/ios/device/routes/condition_route_mixin.rb
lib/calabash/ios/device/routes/error.rb
lib/calabash/ios/device/routes/handle_route_mixin.rb
lib/calabash/ios/device/routes/map_route_mixin.rb
lib/calabash/ios/device/routes/response_parser.rb
lib/calabash/ios/device/routes/uia_route_mixin.rb
spec/lib/ios/device/routes/backdoor_route_mixin_spec.rb
spec/lib/ios/device/routes/condition_route_mixin_spec.rb
spec/lib/ios/device/routes/handle_route_mixin_spec.rb
spec/lib/ios/device/routes/map_route_mixin_spec.rb
spec/lib/ios/device/routes/response_parser_spec.rb
spec/lib/ios/device/routes/uia_route_mixin_spec.rb

Avoiding duplication, makes routes easier to write, fewer specs.

iOS: Generic module for parsing http response bodies

---

calabash.gemspec
cucumber/ios/.irbrc
cucumber/ios/Rakefile
lib/calabash/ios/device/device.rb
lib/calabash/ios/device/routes/uia_route_mixin.rb
lib/calabash/ios/environment.rb
spec/lib/ios/device/routes/uia_route_mixin_spec.rb
spec/lib/ios/environment_spec.rb
spec/spec_helper.rb

Adds missing support for :shared_element and fixes :host strategy.
Calabash responds to the CAL_UIA_STRATEGY variable.

iOS ensure all UIA strategies are working

---

lib/calabash/ios/console_helpers.rb
lib/calabash/ios/device/device.rb
spec/lib/ios/device/device_spec.rb

* Public docs were missing.
* Try to populate @runtime_attributes

iOS: public API docs and enhancements for console_attach

---

lib/calabash/android/device.rb
lib/calabash/http/retriable_client.rb

This allows us to seamlessly automate multiple apps or have multiple endpoints for Android.

Android: React to ECONNREFUSED by forwarding

---

cucumber/ios/features/drag_and_drop.feature
cucumber/ios/features/step_definitions/drag_and_drop_steps.rb
lib/calabash/ios/device/gestures_mixin.rb

```
Scenario: Drag the red box to the left well
When I drag the red box to the left well
Then the well should change color
And the box goes back to its original position
```

iOS: implement pan_between

---

lib/calabash/gestures.rb

* Clarifying the `pan` docs.
* Changed some double quotes to single.

Update gestures docs and style

---

lib/calabash/ios/device/device_implementation.rb

Current log message was confusing and spanned several lines.

iOS: ensure_app_installed - improve diff SHA message

---

samples/wordpress/README.md
samples/wordpress/config/cucumber.yml

Instructions for how to run cucumbers and start a console.
+ 100 @TobiasRoikjer for setting this up.  Looks really nice.  Good job.

Wordpress:  Add a README.md

---

.gitignore
README.md
Rakefile
samples/wordpress/Gemfile.lock

1. Improved rake task docs
2. Better ctags
3. Update README.md with rake tasks
4. Added 'yard:publish' task
5. Added missing Gemfile.lock to samples/wordpress
6. Removed cucumber/x-platform - was replaced by samples/wordpress

Project clean up and documentation

---

lib/calabash/cli/generate.rb
lib/calabash/lib/skeleton/Gemfile

* Scaffold Gemfile is inconsistent #206
Pegs the Gemfile to the current version of Calabash (Calabash::VERSION).
@TobiasRoikjer Does this have tests anywhere?

Improve skeleton Gemfile

---

lib/calabash.rb
lib/calabash/android/physical_buttons.rb
lib/calabash/gestures.rb
lib/calabash/interactions.rb
lib/calabash/ios/device/routes/error.rb
lib/calabash/location.rb
lib/calabash/text.rb

The stats are misleading - they include modules and methods that are _private_ in the undocumented count.
To get detailed stats:
```
$ be yard stats --list-undoc
```
You can find more details in the [README_YARDOC.md](README_YARDOC.md).
```
$ be rake yard
Files:          78
Modules:         8 (    4 undocumented)
Classes:        18 (    5 undocumented)
Constants:      21 (   11 undocumented)
Methods:       454 (  188 undocumented)
58.48% documented
```

Docs:  more doc fixes

---

lib/calabash/lib/skeleton/.gitignore

* Add some inline docs
* Ignore .pry-history
* Ignore pesky MacOS artifacts
* Ignore emacs back up files.

Add content to skeleton .gitignore

---

.gitignore
script/docs/publish-calabash-docs.sh

Ease the pain of publishing docs.

Add the publish-docs script to git

---

lib/calabash/device.rb
lib/calabash/ios/device/gestures_mixin.rb

We'll see how this goes.  All cucumbers are green.

iOS: gestures use the :at offsets in touch

---

cucumber/ios/features/flick.feature
cucumber/ios/features/pan.feature
cucumber/ios/features/step_definitions/flick_steps.rb
cucumber/ios/features/step_definitions/pan_steps.rb
lib/calabash/ios/device/gestures_mixin.rb
lib/calabash/ios/gestures.rb

I don't have any good flick examples other than `flick to go back`.

iOS: implement flick gesture

---

lib/calabash/gestures.rb

In the middle of something else and saw that this needed doing.

Docs: fill in some missing gesture documentation

---

cucumber/ios/features/flick.feature
lib/calabash/ios/device/rotation_mixin.rb

Fixes a mistake made in https://github.com/calabash/calabash/pull/233

iOS: Fixup orientation rotation

---

cucumber/ios/features/animations.feature
cucumber/ios/features/backdoor.feature
cucumber/ios/features/drag_and_drop.feature
cucumber/ios/features/keyboard/keyboard.feature
cucumber/ios/features/keyboard/keyboard_delete.feature
cucumber/ios/features/orientation.feature
cucumber/ios/features/pinch.feature
cucumber/ios/features/scroll.feature
cucumber/ios/features/step_definitions/pinch_steps.rb
cucumber/ios/features/step_definitions/shared_steps.rb
cucumber/ios/features/step_definitions/tap_gestures_steps.rb
cucumber/ios/features/support/dry_run.rb
cucumber/ios/features/tap_gestures.feature
cucumber/ios/features/uia.feature

Had some flickering tests and some that needed to be updated for the new layout on the test app.

iOS: Fixup Cucumbers

---

.travis.yml

http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade

Travis: upgrade to container based runtime

---

cucumber/ios/Gemfile
cucumber/ios/Gemfile.lock
cucumber/ios/features/date_picker.feature
cucumber/ios/features/step_definitions/date_picker_steps.rb
lib/calabash/ios.rb
lib/calabash/ios/date_picker.rb

Implements the Date Picker API.

iOS: Date Picker API

---

cucumber/ios/features/step_definitions/background_steps.rb
lib/calabash/ios/interactions.rb
lib/calabash/life_cycle.rb

I didn't realize this was an abstract method.

iOS: fix send app to background implementation
