calabash.gemspec
There has been discussion about making bundler and bundle exec a requirement for calabash 2.0.
=> Gemspec: bundler will be required for calabash

calabash.gemspec
**FORCE PUSHED**  Tue Jan 27 12:34 CET
Several runtime gems and many development gems are shared by run-loop, which is itself a dependency of this project. 
This pull-request removes the version requirements for shared-gems which will allow run-loop to control which gem version to use.
**UPDATE** Merge after CI passes. :)
=> Remove version dependencies for gems shared with run loop

calabash.gemspec
**FORCE PUSHED** Mon Mar 23 17:26 CET
We want:
```
$ bundle exec calabash [cmd]
```
=> Fix gemspec executable attribute

.travis.yml
Ruby 2.2.* is here, we have to test against it.
=> Feature/add ruby 2.2.1 to travis

lib/calabash/ios/device.rb, spec/lib/ios/device_spec.rb
**Calabash iOS Device needs to retain a reference to the current run-loop.** #36
=> iOS Device needs reference to run-loop

build/android_test_server.rb
This fixes the issue with `$ rake build` failing
=> Build: Properly require calabash/android

bin/calabash, build/android_test_server.rb, calabash.gemspec, lib/calabash.rb, lib/calabash/version.rb
**FORCE MERGE** Tue May 5 13:16 CET
By default, `bundler gem [gemname]` mangles the `$LOAD_PATH`.
http://guides.rubygems.org/patterns/
At its core, RubyGems exists to help you manage Ruby’s $LOAD_PATH, which is how the require statement picks up new code. There’s several things you can do to make sure you’re loading code the right way.
**Respect the global load path**
When packaging your gem files, you need to be careful of what is in your lib directory. Every gem you have installed gets its lib directory appended onto your $LOAD_PATH. This means any file on the top level of the lib directory could get required.
**Mangling the load path**
Gems should not change the $LOAD_PATH variable. RubyGems manages this for you. Code like this should not be necessary:
```
lp = …
```
=> Stop munging the LOAD_PATH

calabash.gemspec, lib/calabash/http/retriable_client.rb, spec/lib/http/retriable_client_spec.rb
We want retriable 2.0.  Run-loop and test-cloud-command-line are now compatible with 1.3.3.1 <= retriable <  2.1.
@TobiasRoikjer The big change here are the args to retriable:
```
Try 3 times with a 2 second wait between each try.
;;; 1.x
Retriable(tries: 3, interval: 2)
;;; 2.0
Retriable(intervals: [2, 2, 2])
```
=> Require retriable 2.0

lib/calabash/ios.rb, lib/calabash/ios/device.rb, lib/calabash/ios/device_runtime_info.rb, lib/calabash/ios/runtime_attributes.rb, spec/integration/ios/device_spec.rb, spec/lib/ios/device_spec.rb, spec/lib/ios/runtime_attributes_spec.rb
Some information about the device and app under test can only be extracted at runtime via a server query.
Many of the Calabash::Cucumber::Device class methods can be replaced be by inspecting the RunLoop::Device class.
Most of the Calabash::Cucumber::Device class methods could be replaced _if_ we could use a third-party tool like `libimobiledevice`.
Some information about the device and app under test can only be extracted at runtime via a server query.
It is not possible to answer all of these questions for physical devices because the UDID of the device is opaque.  We can't know, for example, if the device is an iPad or iPhone 6.
This is only necessary for iOS < 8.0.  It is otherwise unused.  It can only be determined at runtime because of iPhone 6 and iPhone 6 plus scaling and sampling …
=> iOS Device:  Add runtime model

calabash.gemspec
The gemspec was only capturing .rb files.  The .yml files and .irbrc files were not being captured.
=> Include skeleton files and .irbrc in gemspec

lib/calabash/http/error.rb, lib/calabash/http/request.rb, lib/calabash/ios.rb, lib/calabash/ios/device.rb, lib/calabash/ios/routes/error.rb, lib/calabash/ios/routes/map_route.rb, lib/calabash/ios/routes/route_mixin.rb, spec/lib/http/request_spec.rb, spec/lib/ios/routes/map_route_spec.rb, spec/lib/ios/routes/route_mixin_spec.rb
After looking at the UIA route and the map route, I decided there was enough duplication that I should extract into generic methods.
@TobiasRoikjer Do you think you will be able to reuse this on the Android side?
=> Generic route handling mixin by extracting methods from iOS map route

lib/calabash/ios/routes/error.rb, lib/calabash/ios/routes/map_route.rb, lib/calabash/ios/routes/route_mixin.rb, spec/lib/ios/routes/map_route_spec.rb, spec/lib/ios/routes/route_mixin_spec.rb
Replaces error classes for specific routes with a generic RouteError.
I opted to keep the Mixin name for now.
=> Refactor RouteMixin with Tobias's edits

lib/calabash/wait.rb, spec/lib/wait_spec.rb
**Wait::wait_for arguments seem wrong - the timeout parameter should come from the defaults.** #103
=> Wait#wait_for should use default timeout

lib/calabash.rb, lib/calabash/android.rb, lib/calabash/android/api.rb, lib/calabash/api.rb, lib/calabash/ios.rb, lib/calabash/ios/api.rb, spec/lib/api_spec.rb
Operations is an ambiguous word.  This file should be used to expose the Calabash API to Cucumber, rspec, or any other test-runner.
=> Rename operations to api

cucumber/ios/features/support/env.rb, lib/calabash/ios.rb, lib/calabash/ios/api.rb, lib/calabash/ios/api/keyboard.rb, lib/calabash/ios/api/status_bar.rb, lib/calabash/ios/cucumber.rb, lib/calabash/ios/device.rb, spec/lib/ios/api/keyboard_spec.rb, spec/lib/ios/api/status_bar_spec.rb
Now that 'Operations' is 'API' it is clear that we don't need this IOS::Cucumber module.
=> iOS replace 'cucumber' interface with 'api' interface

cucumber/android/features/support/env.rb, cucumber/ios/features/support/env.rb, lib/calabash/ios.rb, lib/calabash/ios/api.rb
I wanted this pattern:
```
require 'calabash/<platform>/api'
World(Calabash::<platform>/API)
```
but it turned out to be impractical and (probably) the wrong pattern.
This is what I have settle on for now:
```
require 'calabash/android'
World(Calabash::Android)
require 'calabash/ios'
World(Calabash::IOS)
```
=> Allow support/env.rb require and World platform

cucumber/ios/features/backdoor.feature, cucumber/ios/features/step_definitions/backdoor_steps.rb, lib/calabash/interactions.rb, lib/calabash/ios/device.rb, lib/calabash/ios/device/device.rb, lib/calabash/ios/device/routes/backdoor_route_mixin.rb, spec/lib/ios/device/routes/backdoor_route_mixin_spec.rb
There were several edge cases not handled by the implementation in iOS::Device.
Add a bunch of Cucumbers that describe the API.
=> iOS: move backdoor implementation to route mixin

cucumber/ios/.irbrc, lib/calabash/ios/console_helpers.rb, lib/calabash/ios/device/device.rb, spec/integration/ios/console_helper_spec.rb, spec/lib/ios/device/device_spec.rb
I encountered some problems with gestures and in order to debug them, I need `console_attach` in the console.
```
$ be rspec spec/integration/ios/console_helpers.rb
```
=> iOS implement console_attach

bin/calabash, lib/calabash/android/build/builder.rb, lib/calabash/android/build/java_keystore.rb, lib/calabash/android/build/resigner.rb, lib/calabash/cli.rb, lib/calabash/cli/helpers.rb, lib/calabash/cli/setup_keystore.rb
- Use the new signing methods from 1.0, which allows DSA certs.
- Add setup-keystore CLI command
- Better error messages regarding keystores in general
=> A: A lot of keystore changes

lib/calabash/ios/device/device.rb, spec/lib/ios/application_spec.rb, spec/lib/ios/device/device_spec.rb, spec/lib/ios/device/uia_keyboard_mixin_spec.rb, spec/lib/wait_spec.rb
It is a good thing I checked:  found two cases where we were masking a NameError incorrectly.
=> Rspec:  fix false-positive warning when testing raise_error

cucumber/ios/features/step_definitions/shared_steps.rb, cucumber/ios/features/step_definitions/uia_steps.rb, cucumber/ios/features/uia.feature, lib/calabash/ios/device/routes/uia_route_mixin.rb, lib/calabash/ios/device/uia_mixin.rb, spec/lib/ios/device/routes/uia_route_mixin_spec.rb, spec/lib/ios/device/uia_mixin_spec.rb
```
Scenario: Tapping
Given I see the first tab
Then I use UIA to touch the text field
And I wait for the keyboard
Then I use UIA to type "Hello"
And the text in the text field should be "Hello"
Then I use UIA to touch the Done button on the keyboard
```
Resolves: **Syntax errors in queries have outcome "success" instead of "failure"** [#374](https://github.com/calabash/calabash-ios/issues/374)
=> iOS: implement uia

cucumber/ios/features/gestures.feature, cucumber/ios/features/step_definitions/gestures_steps.rb, lib/calabash/ios/device/gestures_mixin.rb
Was raising:
```
When I tap a view that does not exist      # features/step_definitions/gesstures_steps.rb:2
undefined local variable or method `screenshot_embed' for
#<#<Class:0x007f9fd410d940>:0x007f9fd410d710>
```
Now raises:
```
#<Calabash::Wait::ViewNotFoundError: Waited 5 seconds for "view marked:'does not exist'" to match a view>
```
=> iOS: tap raises correct error if view is not found

.travis.yml, calabash.gemspec
Why do we depend on cucumber? :)
The only tool that needs this is the run-command.  Otherwise it is not necessary.
I realize we are a cucumber tool, but this change might push folks toward using a Gemfile.
At the very least, let's remove the slowhandcuke dependency _unless_ we are going to included it in the skeleton.
=> Remove cucumber dependency

cucumber/ios/features/gestures.feature, cucumber/ios/features/step_definitions/gestures_steps.rb, lib/calabash/ios/device/gestures_mixin.rb
```
Scenario:  Long press
Given I see the gestures tab
When I long press the box for 1 second
Then the gesture description changes to long press
When I long press the box for 2 seconds
Then the gesture description changes to long press
```
=> iOS: long press

cucumber/ios/features/animations.feature, cucumber/ios/features/step_definitions/animations_steps.rb, lib/calabash/ios/conditions.rb
```
@backdoor
Scenario: Start an animation and wait for it to finish
And I have started an animation that lasts 4 seconds
Then I can wait for the animation to stop
@network_indicator
@backdoor
Scenario: Start the network indicator and wait for it to finish
And I start the network indicator for 4 seconds
Then I can wait for the indicator to stop
Scenario: Call wait_for_animation with a nil query
When I pass an empty query to wait_for_animations_in
Then the app should not crash
And an error should be raised
```
=> iOS: fixup wait for condition API

lib/calabash/ios/conditions.rb
* Default query should be '*' not nil, which will crash the app.
* Return true when condition is met without raising.
=> iOS: conditions API fixup

lib/calabash/ios/device/uia_keyboard_mixin.rb, spec/lib/ios/device/uia_keyboard_mixin_spec.rb
Sometimes there is no `status` key in the results, but the result itself looks like a good result.
(>_O) :8ball:
=> iOS Typing - handle case where there is no 'status' key, but result is a hash with reasonable key/value pairs

lib/calabash/wait.rb, spec/lib/wait_spec.rb
The default 0.3 is too long.
@TobiasRoikjer Agreed?
=> Wait: Reduce the default retry frequency

lib/calabash/ios/device/routes/playback_route_mixin.rb, spec/lib/ios/device/routes/playback_route_mixin_spec.rb
Somewhere along the way, rotation playback caused the next query/gesture to be invalid.
=> iOS: must recalibrate after a rotation

lib/calabash/device.rb
Dumping can take a while, especially for WKWebViews on iOS
=> iOS: Device: #dump: Should have longer timeout

cucumber/ios/config/cucumber.yml, cucumber/ios/features/pan.feature, cucumber/ios/features/step_definitions/pan_steps.rb, cucumber/ios/features/step_definitions/scroll_steps.rb, cucumber/ios/features/support/ideviceinstaller.rb, lib/calabash/ios.rb, lib/calabash/ios/device/gestures_mixin.rb, lib/calabash/ios/runtime.rb, lib/calabash/ios/scroll.rb, spec/lib/ios/scroll_spec.rb
Pan works on iOS Simulators, but never in UIScrollView or UIScrollView subclasses.
```
Scenario: Left-to-right screen pan in portrait
When I touch the table views row
Then I see the table views page
When I pan left on the screen
Then I go back to the Scrolls page
Scenario: Left-to-right screen pan in landscape
And I rotate so the home button is on the right
When I touch the collection views row
Then I see the collection views page
When I pan left on the screen
Then I go back to the Scrolls page
Scenario: Panning on a scroll view
When I touch the scroll views row
Then I see the scroll views page
When I pan to the cayenne box on the simulator
Then I expect an error to be raised about dragInsideWithOptions
But I can pan to the cayenne box on the device
```
=> iOS Pan part 2

.gitignore, cucumber/android/features/support/env.rb, cucumber/ios/.irbrc, cucumber/ios/features/support/env.rb, lib/calabash/android/lib/.irbrc, lib/calabash/console_helpers.rb, lib/calabash/ios/lib/.irbrc
* Try to load pry and pry-nav.
* Add .pry-history so pry doesn't clobber the .irb history.
* Set .pry-history and load pry-nav in cucumber/ projects.
* Display information about help console methods.
* Display a message of the day with the version of Calabash.
* Add verbose and quiet methods to control debug logging.
@TobiasRoikjer 
1. I really need pry in the console.
2. I want to at least print the version of Calabash.
With those two changes, I can almost feel comfortable using the default .irbrc.
We don't have much debug logging do we?
```
$ be calabash console CalSmoke-cal.app
Running irb...
>     ids => List all the visible ids.
> classes => List all the visible classes.
>    tree => The app's visible view hierarchy.
>    copy => Copy console commands to the Clipboard.
> verbose => …
```
=> Improve the console

calabash.gemspec
the gemspec didn't include files necessary to call calabash generate
=> Update gemspec to make generate work

samples/wordpress/Gemfile, samples/wordpress/Gemfile.lock, samples/wordpress/README.md
We need to pin the version to 1.9.9.pre2 (or the most recent release).  Otherwise, we have to mention users must run:
* copy_repos.sh
* change_old_files.sh
* be rake android:build
README.md - There is no need to resign or build the apk; you can just `run`.  Hurray!  +1 @TobiasRoikjer
=> Wordpress: update the gemfile and docs

lib/calabash/gestures.rb
The beautiful Gesture API was marked private.
Made a best guess about what to do re: Android gesture _classes_.
These docs have been published.
http://calabashapi.xamarin.com/calabash/
=> Docs fix gestures docs

cucumber/ios/features/backdoor.feature, cucumber/ios/features/keyboard/keyboard.feature, cucumber/ios/features/keyboard/keyboard_delete.feature, cucumber/ios/features/orientation.feature, cucumber/ios/features/pan.feature, cucumber/ios/features/step_definitions/pan_steps.rb, cucumber/ios/features/step_definitions/shared_steps.rb, cucumber/ios/features/step_definitions/uia_steps.rb, cucumber/ios/features/uia.feature, lib/calabash/ios.rb, lib/calabash/ios/device/gestures_mixin.rb, lib/calabash/ios/gestures.rb
```
@pan
Feature: Pan
In order to perform swipes
As a developer
I want a Pan API
Scenario: Left-to-right screen pan in portrait
Given I see the scrolls tab
When I touch the table views row
Then I see the table views page
When I pan left on the screen
Then I go back to the Scrolls page
Scenario: Left-to-right screen pan in landscape
Given I see the scrolls tab
And I rotate so the home button is on the right
When I touch the collection views row
Then I see the collection views page
When I pan left on the screen
Then I go back to the Scrolls page
Scenario: Panning on a scroll view
Given I see the scrolls tab
When I touch the scroll views row
Then I see the scroll views page
When I pan to the cayenne box on the simulator
Then I expect an error to be raised about dragInsideWithOptions
But I …
```
=> iOS Pan gesture part 3

lib/calabash/version.rb, samples/wordpress/Gemfile, samples/wordpress/Gemfile.lock
Released off the develop branch - not a good practice, but we are in dev mode.
There is one failing/flickering Android test:
```cucumber
Scenario: Adding a self-hosted site               # features/login.feature:6
Given I am on the login screen                  # features/step_definitions/login_steps.rb:29
Then I should be able to add a self-hosted site # features/step_definitions/login_steps.rb:34
Failed to perform gesture. java.lang.SecurityException: Injecting to another application requires INJECT_EVENTS permission (RuntimeError)
./features/android/pages/login_page.rb:50:in `toggle_self_hosted_site'
./features/android/pages/login_page.rb:35:in `enable_self_hosted_site'
./features/step_definitions/login_steps.rb:35:in `/^I should be able to add a self\-hosted site$/' …
```
=> Release 1.9.9.pre3

cucumber/ios/features/step_definitions/orientation_steps.rb, lib/calabash/ios/device/rotation_mixin.rb, lib/calabash/ios/orientation.rb, spec/lib/ios/orientation_spec.rb
Differentiates between a rotate _gesture_ and rotating the device to change orientation.
=> iOS: replace rotate(direction) with rotate_device_left and right_device_right

cucumber/ios/features/pinch.feature, cucumber/ios/features/step_definitions/pinch_steps.rb, lib/calabash/device.rb, lib/calabash/gestures.rb, lib/calabash/ios/device/gestures_mixin.rb, lib/calabash/ios/gestures.rb
```cucumber
Feature: Pinch
In order to zoom in and out
As a developer
I want a Pinch API
Scenario: Pinch in and out on a view
Given I see the gestures tab
And I see the pinching page
When I pinch out on the box, it gets bigger
When I pinch in on the box, it gets smaller
And I can zoom in on the box
And I can zoom out on the box
Scenario: Zoom in and out on a map
Given I see the scrolls tab
And I see the map views page
Then I can zoom out on the map
And I can zoom in on the map
Scenario: Zoom in and out on a map
Given I see the scrolls tab
And I see the map views page
Then I can zoom out on the screen
And I can zoom in on the screen
Scenario: Pinch in and out on the screen
Given I see the scrolls tab
And I see the map views page
Then I can pinch in on the screen
And I can pinch out on the …
```
=> iOS Pinch gesture

cucumber/ios/Gemfile.lock, cucumber/ios/config/cucumber.yml, cucumber/ios/features/slider.feature, cucumber/ios/features/step_definitions/slider_steps.rb, lib/calabash/ios.rb, lib/calabash/ios/slider.rb
```
@slider
Feature: UISlider
In order to interact with sliders
As a developer
I want a Slider API
Scenario: Setting the value of a slider
Given I see the controls tab
Then I can get the min and max values of the slider
And I can set the value of the slider to 8
```
=> iOS: add API for setting the value of a UISlider

cucumber/ios/features/flash.feature, cucumber/ios/features/step_definitions/flash_steps.rb, lib/calabash/console_helpers.rb, lib/calabash/interactions.rb, lib/calabash/ios/device/routes/handle_route_mixin.rb, spec/lib/ios/device/routes/handle_route_mixin_spec.rb
* Easier to test (discovered a bug in iOS implementation).
* Useful debugging tool - even in Scenarios.
* Potentially useful on the XTC with video capture.
=> Move flash to interactions

cucumber/ios/features/runtime.feature, cucumber/ios/features/step_definitions/runtime_steps.rb, lib/calabash/ios/device/device_implementation.rb, lib/calabash/ios/device/runtime_attributes.rb, lib/calabash/ios/runtime.rb, spec/lib/ios/device/device_spec.rb
```
Scenario: The Runtime API
Given the app has launched
Then I can ask if the device is a simulator or physical device
And I can ask if the device is an iPad, iPhone, or iPod
And I can ask if the device is in the iPhone family
And I can ask if the app is an iPhone app emulated on an iPad
And I can ask if the device is a 4in device
And I can ask if the device is a 3.5in device
And I can ask if the device is an iPhone 6 or iPhone 6+
And I can ask for details about the device screen and app display details
And I can ask what version of iOS the device is running
And I can ask for the version of the Calabash iOS Server
And I can ask specific questions about the iOS version
And I can get version information about the app
And I can get a full dump of the runtime attributes
```
=> iOS:  Runtime API

.gitignore, cucumber/ios/features/screenshots.feature, cucumber/ios/features/step_definitions/screenshot_steps.rb
@danwaters asked me how to handle screenshots for Calabash iOS 0.x.
This is how it is done in Calabash 2.0.
```
Background:  The app has launched
Given the app has launched
Scenario: Default screenshot behavior
When I take a screenshot with the default screenshot method
Then the screenshot has a number appended to the name
Scenario: Can name a screenshot
When I take a screenshot and specify the name
Then the screenshot is saved with that name in the default location
Scenario: Save a screenshot to an absolute path
When I take a screenshot and specify an absolute path
Then the screenshot is created where I specified
Scenario: Save a screenshot to a relative path
When I take a screenshot and specify a relative path
Then the screenshot is created where I specified
```
=> iOS Cucumber: screenshots

cucumber/ios/config/cucumber.yml, cucumber/ios/features/background.feature, cucumber/ios/features/step_definitions/background_steps.rb, cucumber/ios/features/support/hooks.rb, lib/calabash/android/interactions.rb, lib/calabash/ios/interactions.rb
```
Scenario: Simulate touching the home button
Then backgrounding the app for less than one second raises an error
And backgrounding the app for more than sixty seconds raises an error
But I can send the app to the background for 1 second
@shared_element
Scenario: Backgrounding works with :shared_element
Then I can background the app when UIA strategy is :shared_element
@host
Scenario: Backgrounding works with :host
Then I can background the app when UIA strategy is :host
@preferences
@simulator_only
Scenario: Background works with :preferences
Then I can background the app when UIA strategy is :preferences
```
=> iOS: send app to background

README.md, Rakefile, cucumber/ios/Gemfile, cucumber/ios/Gemfile.lock, cucumber/ios/README.md, cucumber/ios/Rakefile, cucumber/ios/config/cucumber.yml, cucumber/ios/features/ensure_ipad_1x.feature, cucumber/ios/features/step_definitions/ensure_ipad_1x_steps.rb, cucumber/ios/features/support/env.rb, cucumber/ios/features/support/hooks.rb, lib/calabash/ios/device.rb, lib/calabash/ios/device/device_implementation.rb, lib/calabash/ios/device/ipad_1x_2x_mixin.rb, lib/calabash/ios/device/routes/uia_route_mixin.rb, lib/calabash/ios/runtime.rb, spec/lib/ios/device/device_spec.rb
Calabash cannot translate coordinates from the 2x space.
There is a bug and a failing cucumber:
**Cannot touch views on iPhone apps emulated on iPad - even in 1X mode** [Calabash iOS 0.x #813](https://github.com/calabash/calabash-ios/issues/813)
=> iOS: at launch, ensure iPhone apps emulated on iPad are in 1X zoom
